[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/cs",
    "crates/server",
    "crates/cert",
    "crates/stun",
    "crates/macros",
    "crates/client",
    "crates/client-cli",
    "crates/client-gui",
]

[profile.release]
strip = "symbols"
lto = "fat"
codegen-units = 1
