[package]
name = "memorage-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = { version = "*", features = ["serde"] }
serde = { version = "*", features = ["derive"] }
time = { version = "*", features = ["serde"] }
rand = "0.7"
