[package]
name = "soter-stun"
version = "0.1.0"
edition = "2021"

[dependencies]
soter-core = { path = "../soter-core" }
enumn = "*"
thiserror = "*"
tokio = { version = "*", features = ["net"] }

[dev-dependencies]
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }
